// CheckingAccount.java this class is all the getters and setters to the MEMORY where the
//data is stored
public class CheckingAccount extends BankAccount {//this indicates this class is a child of BankAccount
    private double interestRate;

    public CheckingAccount(double interestRate) {//This shows the interest rate
        //it doesnt do anything unless this program stays on for a year
        this.interestRate = interestRate;
    }

    public void processWithdrawal(double amount) {//This whole method adds an overdraft fee
        //it works if you take more than there is from the account it will take 30 more
        if (getBalance() >= amount) {
            withdrawal(amount);
        } else {
            withdrawal(amount + 30); // Overdraft fee
            System.out.println("Insufficient funds. A $30 overdraft fee has been applied.");
            System.out.println("New balance: $" + getBalance());
        }
    }

    public void displayAccount() {//This method gets called in the VegasBank class
        //and displays this method's information in the main program generated by that class
        accountSummary(); // Call superclass method
        System.out.println("Interest Rate: " + interestRate + "%");
    }

    public String getAccountSummary() { // Added for GUI output
        //I tried to make a GUI class but cant get it to work right
        //I'll putit in my github
        return super.getAccountSummary() + "\n" +
                "Interest Rate: " + interestRate + "%";
    }
}
